services:
  gflow-job:
    build:
      context: .
      dockerfile: ConverterDockerfile
    image: szoshojob:latest
    volumes:
      - ./:/app
    environment:
      - SZOSHO_URL=http://host.docker.internal:28080
      - LOG_LEVEL=INFO
    extra_hosts:
      - "host.docker.internal:host-gateway"

  gflow-app:
    build:
      context: .
      dockerfile: AppDockerfile
    image: gflows-app:latest
    volumes:
      - ./:/app
    environment:
      - AUTO_RESPONSE=y
      - LOG_LEVEL=INFO
      # - RISK_FREE_RATE_URL=http://example.com/risk_free_rate.json # Uncomment and set your URL
      # - TICKERS=588000,588080 # Uncomment to override default tickers

  gflow-server:
    image: ghcr.io/static-web-server/static-web-server:latest
    volumes:
      - ./:/public
